#开关配置文件
spring:
  application:
    name: cashloan-auth
  redis:
    database: 1
    host: 172.31.186.176
    port: 6379
    pool:
    max-active: 20
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      master:
        username: program
        password: 2DH9t^YGpaX6
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-k1a2c3c2ek6oa3rhp.mysql.ap-southeast-5.rds.aliyuncs.com:3306/cashloan?characterEncoding=utf8&useSSL=false
        druid:
          initial-size: 3
          max-active: 8
          min-idle: 2
          max-wait: -1
          min-evictable-idle-time-millis: 30000
          max-evictable-idle-time-millis: 30000
          time-between-eviction-runs-millis: 0
          validation-query: select 1
          validation-query-timeout: -1
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          pool-prepared-statements: true
          max-open-prepared-statements: 100
          filters: stat,wall
          share-prepared-statements: true
      slave:
        one:
          username: program
          password: 2DH9t^YGpaX6
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://rr-k1ayz6637xol71qky.mysql.ap-southeast-5.rds.aliyuncs.com:3306/cashloan?characterEncoding=utf8&useSSL=false
        two:
          username: program
          password: 2DH9t^YGpaX6
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://rr-k1ayz6637xol71qky.mysql.ap-southeast-5.rds.aliyuncs.com:3306/cashloan?characterEncoding=utf8&useSSL=false
  rabbitmq:
    host: 172.31.186.176
    port: 5672
    username: user_admin
    password: mGpEmB5u
  sleuth:
    sampler:
      probability: 0.1 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://172.31.186.172:9411/ # 指定了 Zipkin 服务器的地址

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.zxbit.cashloan.auth.server.entity
  global-config:
    id-type: 3  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

server:
    port: 6861 #启动端口
    undertow:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io-threads: 4
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker-threads: 300
      # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
      # 每块buffer的空间大小,越小的空间被利用越充分
      buffer-size: 1024
      # 是否分配的直接内存
      direct-buffers: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:6801/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:ZSC-JAR01}:${EUREKA_PORT:8761}/eureka/,http://${EUREKA_HOST:ZSC-JAR02}:${EUREKA_PORT:8761}/eureka/
# 用户请求相关属性
jwt:
  token-header: Authorization
  expire: 864000
  # jwt密钥 Token相关
  rsa-secret: xx1WET12^%3^(WE45

# 客户端属性
client:
  id: cashloan-auth
  secret: 123456
  token-header: x-client-token
  expire: 864000
  # 客户端(服务)请求密钥
  rsa-secret: x2318^^(*WRYQWR(QW&T

log:
  path: /home/worker/log/auth
