server:
  port: 8765

eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        home-page-url-path: /
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            defaultZone: http://${EUREKA_HOST:ZSC-JAR01}:${EUREKA_PORT:8761}/eureka/,http://${EUREKA_HOST:ZSC-JAR02}:${EUREKA_PORT:8761}/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

spring:
  application:
      name: cashloan-gateway-efficient
  redis:
      database: 1
      host: 172.31.186.176
      jedis:
        pool:
            max-active: 20
  rabbitmq:
      host: ${RABBIT_MQ_HOST:172.31.186.176}
      port:  ${RABBIT_MQ_PORT:5672}
      username: user_admin
      password: mGpEmB5u
  sleuth:
    sampler:
      probability: 0.1 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://172.31.186.172:9411/ # 指定了 Zipkin 服务器的地址
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # =====================================
      - id: cashloan-auth
        uri: lb://cashloan-auth
        order: 8000
        predicates:
        - Path=/api/auth/**
        filters:
        - StripPrefix=2
      - id: cashloan-admin
        uri: lb://cashloan-admin
        order: 8001
        predicates:
        - Path=/api/admin/**
        filters:
        - StripPrefix=2
      - id: cashloan-app-service
        uri: lb://cashloan-app-service
        order: 8002
        predicates:
        - Path=/api/app/**
        filters:
        - StripPrefix=2
        - name: Retry
          args:
            retries: 3 #重试次数，默认3，不包含本次
            status: 404 #重试response code，默认没有
            statusSeries: 500 #重试response code的系列，100（info），200（success），300（redirect），400（client error），500（server error），默认500
            method: GET #重试的request请求，默认GET
      - id: cashloan-supermarket
        uri: lb://cashloan-supermarket
        order: 8003
        predicates:
        - Path=/api/super/**
        filters:
        - StripPrefix=2
      - id: cashloan-pay-router
        uri: lb://cashloan-pay-router
        order: 8004
        predicates:
        - Path=/api/payrouter/**
        filters:
        - StripPrefix=2

log:
  path: /home/worker/log/gate

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

#登录,安卓短信,注册短信,异步回调
gate:
  ignore:
    startWith: /auth/jwt,/app/loan/regist,/app/loan/sendSms,/admin/asyn,/app/loan/common,/super/marketProduct/listBySelectiveInstallment,/super/marketProduct/listBySelectiveCashLoan,/super/marketProduct/official/getCashLoanList,/super/marketProduct/official/getInstallmentList,/super/marketProduct/official/insertMarketProductDownload,/payrouter/pay/callback


auth:
  serviceId: cashloan-auth
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    id: cashloan-gate  #不填则默认读取spring.application.name
    secret: 123456
